api_platform:
    patch_formats:
        json: ['application/merge-patch+json', 'application/json']
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
        versions: [3]
    collection:
        pagination:
            page_parameter_name: _transaction

